DROP DATABASE IF EXISTS ReadySetGo; 

CREATE DATABASE ReadySetGo;

GRANT ALL PRIVILEGES ON ReadySetGo.* to ross@localhost IDENTIFIED BY 'rossk';

USE ReadySetGo;

DROP TABLE IF EXISTS Users;

CREATE TABLE Users(
    uid INTEGER AUTO_INCREMENT,
	username VARCHAR(128) UNIQUE,
	password VARCHAR(128),
	score INTEGER DEFAULT 0,
	PRIMARY KEY(uid)
);